# Generated by Django 5.0.3 on 2024-03-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('sburl', models.URLField(null=True)),
                ('yturl', models.URLField()),
                ('funny', models.BooleanField()),
                ('show_product_quickly', models.BooleanField()),
                ('patriotic', models.BooleanField()),
                ('celebrity', models.BooleanField()),
                ('danger', models.BooleanField()),
                ('animals', models.BooleanField()),
                ('use_sex', models.BooleanField()),
            ],
        ),
    ]
